### PR TITLE
Add initial tests for DefinitionPrinter (including bug fixes)

### LINKED ISSUE #211: DefinitionPrinter tests
We need to port the test cases for the `DefinitionPrinter` class. The reference implementation can be found here: https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/schemaPrinter-test.js

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #211 

Some parts are still missing:

- [ ] string field test with an escaped default value
- [ ] string field with a default null value (requires #239)
- [ ] string field with non-null integer argument
- [ ] support for printing directives
- [ ] support for printing the introspection schema

### CODE REVIEW

File: tests/Functional/Schema/DefinitionPrinterTest.php [hunk 1]
```diff
@@ -0,0 +1,566 @@
...
+     * @throws \Digia\GraphQL\Error\InvariantException
+     * @throws \Digia\GraphQL\Error\PrintException
+     */
+    private function assertPrintedSchemaEqualsBuiltSchema(string $source): void
+    {
+        $schema = buildSchema($source);
+
+        $printer = new DefinitionPrinter();
+
+        $this->assertEquals($source, $printer->printSchema($schema));
```
Comment (spawnia) [inline tests/Functional/Schema/DefinitionPrinterTest.php]: Would change to `assertSame` since that uses ===

**Comment by Jalle19** [comment]
@spawnia I changed it to use `assertSame`

**Comment by crisu83** [comment]
@Jalle19 Can you please create another issue for the remaining issues? Thanks!
