### PR TITLE
Fix wrong type-hints in ExecutionResult

### LINKED ISSUE #322: Wrong type-hints for errors in ExecutionResult
Getting stuff like this from phpstan:

```
  53     Parameter #2 $errors of class Digia\GraphQL\Execution\ExecutionResult    
         constructor expects array<Digia\GraphQL\Execution\ExecutionException>,   
         array<Digia\GraphQL\Schema\Validation\SchemaValidationException> given.  
  60     Parameter #2 $errors of class Digia\GraphQL\Execution\ExecutionResult    
         constructor expects array<Digia\GraphQL\Execution\ExecutionException>,   
         array<int,                                                               
         Digia\GraphQL\Error\InvariantException|Digia\GraphQL\Language\SyntaxErr  
         orException> given.                                                      
  67     Parameter #2 $errors of class Digia\GraphQL\Execution\ExecutionResult    
         constructor expects array<Digia\GraphQL\Execution\ExecutionException>,   
         array<Digia\GraphQL\Validation\ValidationException> given.
```

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #322

### CODE REVIEW

File: tests/Unit/Execution/ExecutionResultTest.php [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+                    'locations' => null,
+                    'path'      => null
+                ]
+            ]
+        ], $executionResult->toArray());
+
+        // Add another error
+        $executionResult->addError(new GraphQLException('Another error'));
+        $this->assertCount(2, $executionResult->getErrors());
+        $this->assertEquals([
```
Comment (crisu83) [inline tests/Unit/Execution/ExecutionResultTest.php]: I would use `assertSame` instead.
